In [1]:
import numpy as np
import pandas as pd
# se importan librerias a utilizar

In [4]:
# importar datos en google colab
# importamos datos 
from google.colab import files
datos2 = files.upload()
print('/n', datos2)

Saving datos_pandas.csv to datos_pandas (2).csv
/n {'datos_pandas.csv': b'17.9302012052,94.5205919533,320.259529602\r\n97.1446971852,69.5932819844,404.634471526\r\n81.7759007845,5.73764809688,181.485107741\r\n55.8543424175,70.3259016768,321.773638018\r\n49.3665499855,75.1140401571,322.465485583\r\n3.19270246506,29.2562988631,94.6188108954\r\n49.2007840582,86.1444385075,356.348092747\r\n21.882803904,46.8415051959,181.653769226\r\n79.5098627219,87.397355535,423.557743194\r\n88.1538874975,65.2056419279,369.229245443\r\n60.7438543399,99.9576339008,427.605803661\r\n67.4155819451,50.3683096094,292.471821553\r\n48.3181157719,99.1289531425,395.529811407\r\n28.8299719729,87.1849488537,319.031348455\r\n43.853742664,64.4736390798,287.4281441\r\n25.3136940868,83.5452942552,292.768908839\r\n10.807726675,45.6955685904,159.663307674\r\n98.365745882,82.6973935253,438.798963866\r\n29.1469099692,66.3651067611,250.986309034\r\n65.1003018959,33.3538834975,231.711507921\r\n24.6441134909,39.5400527406,163.398160832\r\n37.5598048804,1.34572784158,83.4801551365\r\n88.1645062351,95.1536625708,466.265805791\r\n13.8346208354,25.494048204,100.886430268\r\n64.4108437467,77.2598381277,365.641048062\r\n68.925991798,97.4536007955,426.140015493\r\n39.4884422375,50.8561281903,235.532389457\r\n52.4631776831,59.7765096878,283.291640318\r\n48.4847869797,66.9703542227,298.581440375\r\n8.06208781377,98.2426001448,309.234108782\r\n32.7318877149,18.8535355289,129.610139015\r\n11.6523787962,66.2645117418,224.150542091\r\n13.7303535349,70.4725091314,235.305665631\r\n8.18555176536,41.8519894198,153.484189455\r\n53.6098761481,94.560121637,394.939444253\r\n95.3686098922,47.2955069599,336.126738879\r\n87.3336092062,93.8039343271,449.363351987\r\n66.3576110919,81.8475512843,387.014816485\r\n19.7547175302,65.5233009197,240.389441595\r\n21.1334404504,47.4371819938,177.14828058\r\n22.37386481,25.9556275364,119.61125795\r\n93.9904040537,0.127890520058,196.716166657\r\n86.7201980995,18.413766785,236.260808358\r\n98.9983729904,60.2312656882,384.381344695\r\n3.59396564372,96.2522173231,293.237183045\r\n15.1023633732,92.5569035696,304.890882807\r\n97.8341407695,2.02390810433,201.293598424\r\n19.9382196923,46.7782734632,170.610093035\r\n30.3735111369,58.7775251616,242.373484227\r\n73.2928831485,67.6696277593,353.082991304\r\n52.2309008804,81.9024482531,348.725688557\r\n86.4295761137,66.5402275975,365.959970954\r\n93.4008021441,18.0752459352,235.472381633\r\n13.213460059,91.4888587787,300.606878255\r\n4.59346270394,46.3359315158,145.818745251\r\n15.6692915825,35.5437439971,138.880334695\r\n52.9593597724,68.7202096086,317.163707741\r\n56.8175212312,47.5727319202,254.903631301\r\n51.1335430813,78.0421674552,334.5843335\r\n7.86216471526,17.7290817759,69.3555888141\r\n54.6986037014,92.7445841407,386.859937239\r\n86.3990630133,41.8886945857,294.871713576\r\n11.9475060186,42.9613867358,156.754219545\r\n70.3584010648,83.7062345104,391.806135291\r\n29.0223663255,84.327783082,319.310462851\r\n42.7594799067,97.4933260814,376.291589478\r\n96.2156564389,25.8342825832,280.617043873\r\n53.2277276552,27.9055085669,194.430465068\r\n30.3609896715,0.939644215313,69.6488631767\r\n83.2775653897,73.1793485695,384.597184993\r\n30.1876924786,7.1465385989,89.5390083986\r\n11.7884184617,51.6977608445,181.550682802\r\n18.2924240117,61.9779760484,224.773382884\r\n96.7126676927,9.0291015125,219.567093701\r\n31.0127386947,78.2833824603,298.490216481\r\n11.3972607536,61.728693243,199.944044715\r\n17.3925557906,4.24114086314,43.9156923531\r\n72.1826937267,34.5390721676,256.068378234\r\n73.980020785,3.71649343826,159.372580639\r\n94.4930583509,88.41719702,447.132703621\r\n84.5628207335,20.2411621935,233.078829579\r\n51.7424739723,11.009747964,131.070179635\r\n53.7485903953,60.0251022958,298.814332704\r\n85.0508347563,95.7369969538,451.80352299\r\n46.7772504514,90.2022062395,368.366435952\r\n49.7584341737,52.834494361,254.706774007\r\n24.1192565017,42.1028107802,168.308432759\r\n27.2015764537,29.9787492892,146.34226\r\n7.00959616769,55.876058392,176.810148976\r\n97.6469496688,8.14762512696,219.16028041\r\n1.38298250945,84.9440869198,252.905652954\r\n22.3235303534,27.5150750402,127.570478844\r\n45.0454062325,93.5204022248,375.822340339\r\n40.1639914677,0.161699234822,80.3890193252\r\n53.182739793,8.17031616228,142.718183077\r\n46.4567791559,82.000170914,336.876154384\r\n77.1303006946,95.1887594549,438.460586127\r\n68.600607572,72.5711807231,355.900286918\r\n41.6938871165,69.241125973,284.834636711\r\n4.1426693978,52.2547263792,168.034400947'}

In [5]:
datos1 = pd.read_csv('datos_pandas.csv', header=None)
datos1

            0          1           2
0   17.930201  94.520592  320.259530
1   97.144697  69.593282  404.634472
2   81.775901   5.737648  181.485108
3   55.854342  70.325902  321.773638
4   49.366550  75.114040  322.465486
..        ...        ...         ...
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

[100 rows x 3 columns]

In [6]:
#vamos a usar una lista para importar los datos de un csv, inicializamos la lista
datos=[]
#creamos una lista vacia
print(type(datos))
print('datos: ', datos)

<class 'list'>
datos:  []

In [7]:
#vamos a recorrer el archivo datos_pandas.csv linea a linea con un for. 

#El archivo conviene ponerlo donde tienen la carpeta de trabajo del Jupyter Notebook

#presten especial atención a la indentación de las líneas de código dentro del for

#En Python se usa la indentación para indicar si una línea esta dentro o fuera de un bloque. 

#Se usa en los #bloques for, while, if etc. Si no quiero que la línea este dentro del bloque la "desindento"

for i in open("datos_pandas.csv"): # para el parametro cuando abramos "datos_pandas.csv"

    fila=i.split(',') #los datos de cada fila se van a importar como textos

    dato=list(map(float,fila)) #ahora se convierten a numeros (en python 2 es dato=map(float,fila)

    datos.append(dato) #los agregamos a la lista

In [ ]:
#Pueden probar imprimiendo dentro del bloque (se va a mostrar cada dato que se está leyendo):
for i in open("datos_pandas.csv"):
  #para la variable "i" en el elemento iterable "datos_pandas.csv"

    fila=i.split(',') #los datos de cada fila se van a importar como textos
    # se crea una lista denominada "fila" que contendrá: 
    # la función "split()" devuelve una lista de caracteres de los elementos sepradas según el parámetro pasado dentro de la función
    # en este caso el aprametro pasado sería (",")
    # recordemos que hasta ahora el archivo csv no fue imoprtado a una estructura que lo reconozca como filas y columnas o matricialmente
    # por lo tanto poseemos un archivo plano delimitado por comas
    # entonces luego de esta función obtendremos una lista unica, con todos los datos del csv separados y no de forma plano como en el archivo
    print('\n fila: ', fila)

    dato=list(map(float,fila)) # ahora se convierten a numeros (en python 2 es dato=map(float,fila)
    #convertimos el tipo caracter de la función anterior a float (que estaban contenidos en la lista denominada "fila")
    # La función map() toma una función y una lista y aplica esa función a cada elemento de esa lista, produciendo una nueva lista.
    # vamos a obtener una nueva lista denominada "dato"  que contendra lo mismo que "fila", pero con datos tipo FLOAT
    print('\n dato:', dato)

    datos.append(dato) #los agregamos a la lista
    # La función append() agrega un ítem al final de la lista
    print('\n dato:', dato)
    # en este caso agregamos a la lista "datos", los valores de la lista "dato"
    # recordemos que la lista denominda "datos" la creamos vacia

 fila:  ['17.9302012052', '94.5205919533', '320.259529602\n']

 dato: [17.9302012052, 94.5205919533, 320.259529602]

 dato: [17.9302012052, 94.5205919533, 320.259529602]

 fila:  ['97.1446971852', '69.5932819844', '404.634471526\n']

 dato: [97.1446971852, 69.5932819844, 404.634471526]

 dato: [97.1446971852, 69.5932819844, 404.634471526]

 fila:  ['81.7759007845', '5.73764809688', '181.485107741\n']

 dato: [81.7759007845, 5.73764809688, 181.485107741]

 dato: [81.7759007845, 5.73764809688, 181.485107741]

 fila:  ['55.8543424175', '70.3259016768', '321.773638018\n']

 dato: [55.8543424175, 70.3259016768, 321.773638018]

 dato: [55.8543424175, 70.3259016768, 321.773638018]

 fila:  ['49.3665499855', '75.1140401571', '322.465485583\n']

 dato: [49.3665499855, 75.1140401571, 322.465485583]

 dato: [49.3665499855, 75.1140401571, 322.465485583]

 fila:  ['3.19270246506', '29.2562988631', '94.6188108954\n']

 dato: [3.19270246506, 29.2562988631, 94.6188108954]

 dato: [3.19270246506, 29.2562988631, 94.6188108954]

 fila:  ['49.2007840582', '86.1444385075', '356.348092747\n']

 dato: [49.2007840582, 86.1444385075, 356.348092747]

 dato: [49.2007840582, 86.1444385075, 356.348092747]

 fila:  ['21.882803904', '46.8415051959', '181.653769226\n']

 dato: [21.882803904, 46.8415051959, 181.653769226]

 dato: [21.882803904, 46.8415051959, 181.653769226]

 fila:  ['79.5098627219', '87.397355535', '423.557743194\n']

 dato: [79.5098627219, 87.397355535, 423.557743194]

 dato: [79.5098627219, 87.397355535, 423.557743194]

 fila:  ['88.1538874975', '65.2056419279', '369.229245443\n']

 dato: [88.1538874975, 65.2056419279, 369.229245443]

 dato: [88.1538874975, 65.2056419279, 369.229245443]

 fila:  ['60.7438543399', '99.9576339008', '427.605803661\n']

 dato: [60.7438543399, 99.9576339008, 427.605803661]

 dato: [60.7438543399, 99.9576339008, 427.605803661]

 fila:  ['67.4155819451', '50.3683096094', '292.471821553\n']

 dato: [67.4155819451, 50.3683096094, 292.471821553]

 dato: [67.4155819451, 50.3683096094, 292.471821553]

 fila:  ['48.3181157719', '99.1289531425', '395.529811407\n']

 dato: [48.3181157719, 99.1289531425, 395.529811407]

 dato: [48.3181157719, 99.1289531425, 395.529811407]

 fila:  ['28.8299719729', '87.1849488537', '319.031348455\n']

 dato: [28.8299719729, 87.1849488537, 319.031348455]

 dato: [28.8299719729, 87.1849488537, 319.031348455]

 fila:  ['43.853742664', '64.4736390798', '287.4281441\n']

 dato: [43.853742664, 64.4736390798, 287.4281441]

 dato: [43.853742664, 64.4736390798, 287.4281441]

 fila:  ['25.3136940868', '83.5452942552', '292.768908839\n']

 dato: [25.3136940868, 83.5452942552, 292.768908839]

 dato: [25.3136940868, 83.5452942552, 292.768908839]

 fila:  ['10.807726675', '45.6955685904', '159.663307674\n']

 dato: [10.807726675, 45.6955685904, 159.663307674]

 dato: [10.807726675, 45.6955685904, 159.663307674]

 fila:  ['98.365745882', '82.6973935253', '438.798963866\n']

 dato: [98.365745882, 82.6973935253, 438.798963866]

 dato: [98.365745882, 82.6973935253, 438.798963866]

 fila:  ['29.1469099692', '66.3651067611', '250.986309034\n']

 dato: [29.1469099692, 66.3651067611, 250.986309034]

 dato: [29.1469099692, 66.3651067611, 250.986309034]

 fila:  ['65.1003018959', '33.3538834975', '231.711507921\n']

 dato: [65.1003018959, 33.3538834975, 231.711507921]

 dato: [65.1003018959, 33.3538834975, 231.711507921]

 fila:  ['24.6441134909', '39.5400527406', '163.398160832\n']

 dato: [24.6441134909, 39.5400527406, 163.398160832]

 dato: [24.6441134909, 39.5400527406, 163.398160832]

 fila:  ['37.5598048804', '1.34572784158', '83.4801551365\n']

 dato: [37.5598048804, 1.34572784158, 83.4801551365]

 dato: [37.5598048804, 1.34572784158, 83.4801551365]

 fila:  ['88.1645062351', '95.1536625708', '466.265805791\n']

 dato: [88.1645062351, 95.1536625708, 466.265805791]

 dato: [88.1645062351, 95.1536625708, 466.265805791]

 fila:  ['13.8346208354', '25.494048204', '100.886430268\n']

 dato: [13.8346208354, 25.494048204, 100.886430268]

 dato: [13.8346208354, 25.494048204, 100.886430268]

 fila:  ['64.4108437467', '77.2598381277', '365.641048062\n']

 dato: [64.4108437467, 77.2598381277, 365.641048062]

 dato: [64.4108437467, 77.2598381277, 365.641048062]

 fila:  ['68.925991798', '97.4536007955', '426.140015493\n']

 dato: [68.925991798, 97.4536007955, 426.140015493]

 dato: [68.925991798, 97.4536007955, 426.140015493]

 fila:  ['39.4884422375', '50.8561281903', '235.532389457\n']

 dato: [39.4884422375, 50.8561281903, 235.532389457]

 dato: [39.4884422375, 50.8561281903, 235.532389457]

 fila:  ['52.4631776831', '59.7765096878', '283.291640318\n']

 dato: [52.4631776831, 59.7765096878, 283.291640318]

 dato: [52.4631776831, 59.7765096878, 283.291640318]

 fila:  ['48.4847869797', '66.9703542227', '298.581440375\n']

 dato: [48.4847869797, 66.9703542227, 298.581440375]

 dato: [48.4847869797, 66.9703542227, 298.581440375]

 fila:  ['8.06208781377', '98.2426001448', '309.234108782\n']

 dato: [8.06208781377, 98.2426001448, 309.234108782]

 dato: [8.06208781377, 98.2426001448, 309.234108782]

 fila:  ['32.7318877149', '18.8535355289', '129.610139015\n']

 dato: [32.7318877149, 18.8535355289, 129.610139015]

 dato: [32.7318877149, 18.8535355289, 129.610139015]

 fila:  ['11.6523787962', '66.2645117418', '224.150542091\n']

 dato: [11.6523787962, 66.2645117418, 224.150542091]

 dato: [11.6523787962, 66.2645117418, 224.150542091]

 fila:  ['13.7303535349', '70.4725091314', '235.305665631\n']

 dato: [13.7303535349, 70.4725091314, 235.305665631]

 dato: [13.7303535349, 70.4725091314, 235.305665631]

 fila:  ['8.18555176536', '41.8519894198', '153.484189455\n']

 dato: [8.18555176536, 41.8519894198, 153.484189455]

 dato: [8.18555176536, 41.8519894198, 153.484189455]

 fila:  ['53.6098761481', '94.560121637', '394.939444253\n']

 dato: [53.6098761481, 94.560121637, 394.939444253]

 dato: [53.6098761481, 94.560121637, 394.939444253]

 fila:  ['95.3686098922', '47.2955069599', '336.126738879\n']

 dato: [95.3686098922, 47.2955069599, 336.126738879]

 dato: [95.3686098922, 47.2955069599, 336.126738879]

 fila:  ['87.3336092062', '93.8039343271', '449.363351987\n']

 dato: [87.3336092062, 93.8039343271, 449.363351987]

 dato: [87.3336092062, 93.8039343271, 449.363351987]

 fila:  ['66.3576110919', '81.8475512843', '387.014816485\n']

 dato: [66.3576110919, 81.8475512843, 387.014816485]

 dato: [66.3576110919, 81.8475512843, 387.014816485]

 fila:  ['19.7547175302', '65.5233009197', '240.389441595\n']

 dato: [19.7547175302, 65.5233009197, 240.389441595]

 dato: [19.7547175302, 65.5233009197, 240.389441595]

 fila:  ['21.1334404504', '47.4371819938', '177.14828058\n']

 dato: [21.1334404504, 47.4371819938, 177.14828058]

 dato: [21.1334404504, 47.4371819938, 177.14828058]

 fila:  ['22.37386481', '25.9556275364', '119.61125795\n']

 dato: [22.37386481, 25.9556275364, 119.61125795]

 dato: [22.37386481, 25.9556275364, 119.61125795]

 fila:  ['93.9904040537', '0.127890520058', '196.716166657\n']

 dato: [93.9904040537, 0.127890520058, 196.716166657]

 dato: [93.9904040537, 0.127890520058, 196.716166657]

 fila:  ['86.7201980995', '18.413766785', '236.260808358\n']

 dato: [86.7201980995, 18.413766785, 236.260808358]

 dato: [86.7201980995, 18.413766785, 236.260808358]

 fila:  ['98.9983729904', '60.2312656882', '384.381344695\n']

 dato: [98.9983729904, 60.2312656882, 384.381344695]

 dato: [98.9983729904, 60.2312656882, 384.381344695]

 fila:  ['3.59396564372', '96.2522173231', '293.237183045\n']

 dato: [3.59396564372, 96.2522173231, 293.237183045]

 dato: [3.59396564372, 96.2522173231, 293.237183045]

 fila:  ['15.1023633732', '92.5569035696', '304.890882807\n']

 dato: [15.1023633732, 92.5569035696, 304.890882807]

 dato: [15.1023633732, 92.5569035696, 304.890882807]

 fila:  ['97.8341407695', '2.02390810433', '201.293598424\n']

 dato: [97.8341407695, 2.02390810433, 201.293598424]

 dato: [97.8341407695, 2.02390810433, 201.293598424]

 fila:  ['19.9382196923', '46.7782734632', '170.610093035\n']

 dato: [19.9382196923, 46.7782734632, 170.610093035]

 dato: [19.9382196923, 46.7782734632, 170.610093035]

 fila:  ['30.3735111369', '58.7775251616', '242.373484227\n']

 dato: [30.3735111369, 58.7775251616, 242.373484227]

 dato: [30.3735111369, 58.7775251616, 242.373484227]

 fila:  ['73.2928831485', '67.6696277593', '353.082991304\n']

 dato: [73.2928831485, 67.6696277593, 353.082991304]

 dato: [73.2928831485, 67.6696277593, 353.082991304]

 fila:  ['52.2309008804', '81.9024482531', '348.725688557\n']

 dato: [52.2309008804, 81.9024482531, 348.725688557]

 dato: [52.2309008804, 81.9024482531, 348.725688557]

 fila:  ['86.4295761137', '66.5402275975', '365.959970954\n']

 dato: [86.4295761137, 66.5402275975, 365.959970954]

 dato: [86.4295761137, 66.5402275975, 365.959970954]

 fila:  ['93.4008021441', '18.0752459352', '235.472381633\n']

 dato: [93.4008021441, 18.0752459352, 235.472381633]

 dato: [93.4008021441, 18.0752459352, 235.472381633]

 fila:  ['13.213460059', '91.4888587787', '300.606878255\n']

 dato: [13.213460059, 91.4888587787, 300.606878255]

 dato: [13.213460059, 91.4888587787, 300.606878255]

 fila:  ['4.59346270394', '46.3359315158', '145.818745251\n']

 dato: [4.59346270394, 46.3359315158, 145.818745251]

 dato: [4.59346270394, 46.3359315158, 145.818745251]

 fila:  ['15.6692915825', '35.5437439971', '138.880334695\n']

 dato: [15.6692915825, 35.5437439971, 138.880334695]

 dato: [15.6692915825, 35.5437439971, 138.880334695]

 fila:  ['52.9593597724', '68.7202096086', '317.163707741\n']

 dato: [52.9593597724, 68.7202096086, 317.163707741]

 dato: [52.9593597724, 68.7202096086, 317.163707741]

 fila:  ['56.8175212312', '47.5727319202', '254.903631301\n']

 dato: [56.8175212312, 47.5727319202, 254.903631301]

 dato: [56.8175212312, 47.5727319202, 254.903631301]

 fila:  ['51.1335430813', '78.0421674552', '334.5843335\n']

 dato: [51.1335430813, 78.0421674552, 334.5843335]

 dato: [51.1335430813, 78.0421674552, 334.5843335]

 fila:  ['7.86216471526', '17.7290817759', '69.3555888141\n']

 dato: [7.86216471526, 17.7290817759, 69.3555888141]

 dato: [7.86216471526, 17.7290817759, 69.3555888141]

 fila:  ['54.6986037014', '92.7445841407', '386.859937239\n']

 dato: [54.6986037014, 92.7445841407, 386.859937239]

 dato: [54.6986037014, 92.7445841407, 386.859937239]

 fila:  ['86.3990630133', '41.8886945857', '294.871713576\n']

 dato: [86.3990630133, 41.8886945857, 294.871713576]

 dato: [86.3990630133, 41.8886945857, 294.871713576]

 fila:  ['11.9475060186', '42.9613867358', '156.754219545\n']

 dato: [11.9475060186, 42.9613867358, 156.754219545]

 dato: [11.9475060186, 42.9613867358, 156.754219545]

 fila:  ['70.3584010648', '83.7062345104', '391.806135291\n']

 dato: [70.3584010648, 83.7062345104, 391.806135291]

 dato: [70.3584010648, 83.7062345104, 391.806135291]

 fila:  ['29.0223663255', '84.327783082', '319.310462851\n']

 dato: [29.0223663255, 84.327783082, 319.310462851]

 dato: [29.0223663255, 84.327783082, 319.310462851]

 fila:  ['42.7594799067', '97.4933260814', '376.291589478\n']

 dato: [42.7594799067, 97.4933260814, 376.291589478]

 dato: [42.7594799067, 97.4933260814, 376.291589478]

 fila:  ['96.2156564389', '25.8342825832', '280.617043873\n']

 dato: [96.2156564389, 25.8342825832, 280.617043873]

 dato: [96.2156564389, 25.8342825832, 280.617043873]

 fila:  ['53.2277276552', '27.9055085669', '194.430465068\n']

 dato: [53.2277276552, 27.9055085669, 194.430465068]

 dato: [53.2277276552, 27.9055085669, 194.430465068]

 fila:  ['30.3609896715', '0.939644215313', '69.6488631767\n']

 dato: [30.3609896715, 0.939644215313, 69.6488631767]

 dato: [30.3609896715, 0.939644215313, 69.6488631767]

 fila:  ['83.2775653897', '73.1793485695', '384.597184993\n']

 dato: [83.2775653897, 73.1793485695, 384.597184993]

 dato: [83.2775653897, 73.1793485695, 384.597184993]

 fila:  ['30.1876924786', '7.1465385989', '89.5390083986\n']

 dato: [30.1876924786, 7.1465385989, 89.5390083986]

 dato: [30.1876924786, 7.1465385989, 89.5390083986]

 fila:  ['11.7884184617', '51.6977608445', '181.550682802\n']

 dato: [11.7884184617, 51.6977608445, 181.550682802]

 dato: [11.7884184617, 51.6977608445, 181.550682802]

 fila:  ['18.2924240117', '61.9779760484', '224.773382884\n']

 dato: [18.2924240117, 61.9779760484, 224.773382884]

 dato: [18.2924240117, 61.9779760484, 224.773382884]

 fila:  ['96.7126676927', '9.0291015125', '219.567093701\n']

 dato: [96.7126676927, 9.0291015125, 219.567093701]

 dato: [96.7126676927, 9.0291015125, 219.567093701]

 fila:  ['31.0127386947', '78.2833824603', '298.490216481\n']

 dato: [31.0127386947, 78.2833824603, 298.490216481]

 dato: [31.0127386947, 78.2833824603, 298.490216481]

 fila:  ['11.3972607536', '61.728693243', '199.944044715\n']

 dato: [11.3972607536, 61.728693243, 199.944044715]

 dato: [11.3972607536, 61.728693243, 199.944044715]

 fila:  ['17.3925557906', '4.24114086314', '43.9156923531\n']

 dato: [17.3925557906, 4.24114086314, 43.9156923531]

 dato: [17.3925557906, 4.24114086314, 43.9156923531]

 fila:  ['72.1826937267', '34.5390721676', '256.068378234\n']

 dato: [72.1826937267, 34.5390721676, 256.068378234]

 dato: [72.1826937267, 34.5390721676, 256.068378234]

 fila:  ['73.980020785', '3.71649343826', '159.372580639\n']

 dato: [73.980020785, 3.71649343826, 159.372580639]

 dato: [73.980020785, 3.71649343826, 159.372580639]

 fila:  ['94.4930583509', '88.41719702', '447.132703621\n']

 dato: [94.4930583509, 88.41719702, 447.132703621]

 dato: [94.4930583509, 88.41719702, 447.132703621]

 fila:  ['84.5628207335', '20.2411621935', '233.078829579\n']

 dato: [84.5628207335, 20.2411621935, 233.078829579]

 dato: [84.5628207335, 20.2411621935, 233.078829579]

 fila:  ['51.7424739723', '11.009747964', '131.070179635\n']

 dato: [51.7424739723, 11.009747964, 131.070179635]

 dato: [51.7424739723, 11.009747964, 131.070179635]

 fila:  ['53.7485903953', '60.0251022958', '298.814332704\n']

 dato: [53.7485903953, 60.0251022958, 298.814332704]

 dato: [53.7485903953, 60.0251022958, 298.814332704]

 fila:  ['85.0508347563', '95.7369969538', '451.80352299\n']

 dato: [85.0508347563, 95.7369969538, 451.80352299]

 dato: [85.0508347563, 95.7369969538, 451.80352299]

 fila:  ['46.7772504514', '90.2022062395', '368.366435952\n']

 dato: [46.7772504514, 90.2022062395, 368.366435952]

 dato: [46.7772504514, 90.2022062395, 368.366435952]

 fila:  ['49.7584341737', '52.834494361', '254.706774007\n']

 dato: [49.7584341737, 52.834494361, 254.706774007]

 dato: [49.7584341737, 52.834494361, 254.706774007]

 fila:  ['24.1192565017', '42.1028107802', '168.308432759\n']

 dato: [24.1192565017, 42.1028107802, 168.308432759]

 dato: [24.1192565017, 42.1028107802, 168.308432759]

 fila:  ['27.2015764537', '29.9787492892', '146.34226\n']

 dato: [27.2015764537, 29.9787492892, 146.34226]

 dato: [27.2015764537, 29.9787492892, 146.34226]

 fila:  ['7.00959616769', '55.876058392', '176.810148976\n']

 dato: [7.00959616769, 55.876058392, 176.810148976]

 dato: [7.00959616769, 55.876058392, 176.810148976]

 fila:  ['97.6469496688', '8.14762512696', '219.16028041\n']

 dato: [97.6469496688, 8.14762512696, 219.16028041]

 dato: [97.6469496688, 8.14762512696, 219.16028041]

 fila:  ['1.38298250945', '84.9440869198', '252.905652954\n']

 dato: [1.38298250945, 84.9440869198, 252.905652954]

 dato: [1.38298250945, 84.9440869198, 252.905652954]

 fila:  ['22.3235303534', '27.5150750402', '127.570478844\n']

 dato: [22.3235303534, 27.5150750402, 127.570478844]

 dato: [22.3235303534, 27.5150750402, 127.570478844]

 fila:  ['45.0454062325', '93.5204022248', '375.822340339\n']

 dato: [45.0454062325, 93.5204022248, 375.822340339]

 dato: [45.0454062325, 93.5204022248, 375.822340339]

 fila:  ['40.1639914677', '0.161699234822', '80.3890193252\n']

 dato: [40.1639914677, 0.161699234822, 80.3890193252]

 dato: [40.1639914677, 0.161699234822, 80.3890193252]

 fila:  ['53.182739793', '8.17031616228', '142.718183077\n']

 dato: [53.182739793, 8.17031616228, 142.718183077]

 dato: [53.182739793, 8.17031616228, 142.718183077]

 fila:  ['46.4567791559', '82.000170914', '336.876154384\n']

 dato: [46.4567791559, 82.000170914, 336.876154384]

 dato: [46.4567791559, 82.000170914, 336.876154384]

 fila:  ['77.1303006946', '95.1887594549', '438.460586127\n']

 dato: [77.1303006946, 95.1887594549, 438.460586127]

 dato: [77.1303006946, 95.1887594549, 438.460586127]

 fila:  ['68.600607572', '72.5711807231', '355.900286918\n']

 dato: [68.600607572, 72.5711807231, 355.900286918]

 dato: [68.600607572, 72.5711807231, 355.900286918]

 fila:  ['41.6938871165', '69.241125973', '284.834636711\n']

 dato: [41.6938871165, 69.241125973, 284.834636711]

 dato: [41.6938871165, 69.241125973, 284.834636711]

 fila:  ['4.1426693978', '52.2547263792', '168.034400947']

 dato: [4.1426693978, 52.2547263792, 168.034400947]

 dato: [4.1426693978, 52.2547263792, 168.034400947]

In [ ]:
#Pueden probar imprimiendo fuera del bloque (solo van a ver el último dato leído):

for i in open("datos_pandas.csv"):

    fila=i.split(',') #los datos de cada fila se van a importar como textos

    dato=list(map(float,fila)) #ahora se convierten a numeros (en python 2 es dato=map(float,fila)

    datos.append(dato) #los agregamos a la lista

datos

[[17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],
 [65.1003018959, 33.3538834975, 231.711507921],
 [24.6441134909, 39.5400527406, 163.398160832],
 [37.5598048804, 1.34572784158, 83.4801551365],
 [88.1645062351, 95.1536625708, 466.265805791],
 [13.8346208354, 25.494048204, 100.886430268],
 [64.4108437467, 77.2598381277, 365.641048062],
 [68.925991798, 97.4536007955, 426.140015493],
 [39.4884422375, 50.8561281903, 235.532389457],
 [52.4631776831, 59.7765096878, 283.291640318],
 [48.4847869797, 66.9703542227, 298.581440375],
 [8.06208781377, 98.2426001448, 309.234108782],
 [32.7318877149, 18.8535355289, 129.610139015],
 [11.6523787962, 66.2645117418, 224.150542091],
 [13.7303535349, 70.4725091314, 235.305665631],
 [8.18555176536, 41.8519894198, 153.484189455],
 [53.6098761481, 94.560121637, 394.939444253],
 [95.3686098922, 47.2955069599, 336.126738879],
 [87.3336092062, 93.8039343271, 449.363351987],
 [66.3576110919, 81.8475512843, 387.014816485],
 [19.7547175302, 65.5233009197, 240.389441595],
 [21.1334404504, 47.4371819938, 177.14828058],
 [22.37386481, 25.9556275364, 119.61125795],
 [93.9904040537, 0.127890520058, 196.716166657],
 [86.7201980995, 18.413766785, 236.260808358],
 [98.9983729904, 60.2312656882, 384.381344695],
 [3.59396564372, 96.2522173231, 293.237183045],
 [15.1023633732, 92.5569035696, 304.890882807],
 [97.8341407695, 2.02390810433, 201.293598424],
 [19.9382196923, 46.7782734632, 170.610093035],
 [30.3735111369, 58.7775251616, 242.373484227],
 [73.2928831485, 67.6696277593, 353.082991304],
 [52.2309008804, 81.9024482531, 348.725688557],
 [86.4295761137, 66.5402275975, 365.959970954],
 [93.4008021441, 18.0752459352, 235.472381633],
 [13.213460059, 91.4888587787, 300.606878255],
 [4.59346270394, 46.3359315158, 145.818745251],
 [15.6692915825, 35.5437439971, 138.880334695],
 [52.9593597724, 68.7202096086, 317.163707741],
 [56.8175212312, 47.5727319202, 254.903631301],
 [51.1335430813, 78.0421674552, 334.5843335],
 [7.86216471526, 17.7290817759, 69.3555888141],
 [54.6986037014, 92.7445841407, 386.859937239],
 [86.3990630133, 41.8886945857, 294.871713576],
 [11.9475060186, 42.9613867358, 156.754219545],
 [70.3584010648, 83.7062345104, 391.806135291],
 [29.0223663255, 84.327783082, 319.310462851],
 [42.7594799067, 97.4933260814, 376.291589478],
 [96.2156564389, 25.8342825832, 280.617043873],
 [53.2277276552, 27.9055085669, 194.430465068],
 [30.3609896715, 0.939644215313, 69.6488631767],
 [83.2775653897, 73.1793485695, 384.597184993],
 [30.1876924786, 7.1465385989, 89.5390083986],
 [11.7884184617, 51.6977608445, 181.550682802],
 [18.2924240117, 61.9779760484, 224.773382884],
 [96.7126676927, 9.0291015125, 219.567093701],
 [31.0127386947, 78.2833824603, 298.490216481],
 [11.3972607536, 61.728693243, 199.944044715],
 [17.3925557906, 4.24114086314, 43.9156923531],
 [72.1826937267, 34.5390721676, 256.068378234],
 [73.980020785, 3.71649343826, 159.372580639],
 [94.4930583509, 88.41719702, 447.132703621],
 [84.5628207335, 20.2411621935, 233.078829579],
 [51.7424739723, 11.009747964, 131.070179635],
 [53.7485903953, 60.0251022958, 298.814332704],
 [85.0508347563, 95.7369969538, 451.80352299],
 [46.7772504514, 90.2022062395, 368.366435952],
 [49.7584341737, 52.834494361, 254.706774007],
 [24.1192565017, 42.1028107802, 168.308432759],
 [27.2015764537, 29.9787492892, 146.34226],
 [7.00959616769, 55.876058392, 176.810148976],
 [97.6469496688, 8.14762512696, 219.16028041],
 [1.38298250945, 84.9440869198, 252.905652954],
 [22.3235303534, 27.5150750402, 127.570478844],
 [45.0454062325, 93.5204022248, 375.822340339],
 [40.1639914677, 0.161699234822, 80.3890193252],
 [53.182739793, 8.17031616228, 142.718183077],
 [46.4567791559, 82.000170914, 336.876154384],
 [77.1303006946, 95.1887594549, 438.460586127],
 [68.600607572, 72.5711807231, 355.900286918],
 [41.6938871165, 69.241125973, 284.834636711],
 [4.1426693978, 52.2547263792, 168.034400947],
 [17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],
 [65.1003018959, 33.3538834975, 231.711507921],
 [24.6441134909, 39.5400527406, 163.398160832],
 [37.5598048804, 1.34572784158, 83.4801551365],
 [88.1645062351, 95.1536625708, 466.265805791],
 [13.8346208354, 25.494048204, 100.886430268],
 [64.4108437467, 77.2598381277, 365.641048062],
 [68.925991798, 97.4536007955, 426.140015493],
 [39.4884422375, 50.8561281903, 235.532389457],
 [52.4631776831, 59.7765096878, 283.291640318],
 [48.4847869797, 66.9703542227, 298.581440375],
 [8.06208781377, 98.2426001448, 309.234108782],
 [32.7318877149, 18.8535355289, 129.610139015],
 [11.6523787962, 66.2645117418, 224.150542091],
 [13.7303535349, 70.4725091314, 235.305665631],
 [8.18555176536, 41.8519894198, 153.484189455],
 [53.6098761481, 94.560121637, 394.939444253],
 [95.3686098922, 47.2955069599, 336.126738879],
 [87.3336092062, 93.8039343271, 449.363351987],
 [66.3576110919, 81.8475512843, 387.014816485],
 [19.7547175302, 65.5233009197, 240.389441595],
 [21.1334404504, 47.4371819938, 177.14828058],
 [22.37386481, 25.9556275364, 119.61125795],
 [93.9904040537, 0.127890520058, 196.716166657],
 [86.7201980995, 18.413766785, 236.260808358],
 [98.9983729904, 60.2312656882, 384.381344695],
 [3.59396564372, 96.2522173231, 293.237183045],
 [15.1023633732, 92.5569035696, 304.890882807],
 [97.8341407695, 2.02390810433, 201.293598424],
 [19.9382196923, 46.7782734632, 170.610093035],
 [30.3735111369, 58.7775251616, 242.373484227],
 [73.2928831485, 67.6696277593, 353.082991304],
 [52.2309008804, 81.9024482531, 348.725688557],
 [86.4295761137, 66.5402275975, 365.959970954],
 [93.4008021441, 18.0752459352, 235.472381633],
 [13.213460059, 91.4888587787, 300.606878255],
 [4.59346270394, 46.3359315158, 145.818745251],
 [15.6692915825, 35.5437439971, 138.880334695],
 [52.9593597724, 68.7202096086, 317.163707741],
 [56.8175212312, 47.5727319202, 254.903631301],
 [51.1335430813, 78.0421674552, 334.5843335],
 [7.86216471526, 17.7290817759, 69.3555888141],
 [54.6986037014, 92.7445841407, 386.859937239],
 [86.3990630133, 41.8886945857, 294.871713576],
 [11.9475060186, 42.9613867358, 156.754219545],
 [70.3584010648, 83.7062345104, 391.806135291],
 [29.0223663255, 84.327783082, 319.310462851],
 [42.7594799067, 97.4933260814, 376.291589478],
 [96.2156564389, 25.8342825832, 280.617043873],
 [53.2277276552, 27.9055085669, 194.430465068],
 [30.3609896715, 0.939644215313, 69.6488631767],
 [83.2775653897, 73.1793485695, 384.597184993],
 [30.1876924786, 7.1465385989, 89.5390083986],
 [11.7884184617, 51.6977608445, 181.550682802],
 [18.2924240117, 61.9779760484, 224.773382884],
 [96.7126676927, 9.0291015125, 219.567093701],
 [31.0127386947, 78.2833824603, 298.490216481],
 [11.3972607536, 61.728693243, 199.944044715],
 [17.3925557906, 4.24114086314, 43.9156923531],
 [72.1826937267, 34.5390721676, 256.068378234],
 [73.980020785, 3.71649343826, 159.372580639],
 [94.4930583509, 88.41719702, 447.132703621],
 [84.5628207335, 20.2411621935, 233.078829579],
 [51.7424739723, 11.009747964, 131.070179635],
 [53.7485903953, 60.0251022958, 298.814332704],
 [85.0508347563, 95.7369969538, 451.80352299],
 [46.7772504514, 90.2022062395, 368.366435952],
 [49.7584341737, 52.834494361, 254.706774007],
 [24.1192565017, 42.1028107802, 168.308432759],
 [27.2015764537, 29.9787492892, 146.34226],
 [7.00959616769, 55.876058392, 176.810148976],
 [97.6469496688, 8.14762512696, 219.16028041],
 [1.38298250945, 84.9440869198, 252.905652954],
 [22.3235303534, 27.5150750402, 127.570478844],
 [45.0454062325, 93.5204022248, 375.822340339],
 [40.1639914677, 0.161699234822, 80.3890193252],
 [53.182739793, 8.17031616228, 142.718183077],
 [46.4567791559, 82.000170914, 336.876154384],
 [77.1303006946, 95.1887594549, 438.460586127],
 [68.600607572, 72.5711807231, 355.900286918],
 [41.6938871165, 69.241125973, 284.834636711],
 [4.1426693978, 52.2547263792, 168.034400947],
 [17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],
 [65.1003018959, 33.3538834975, 231.711507921],
 [24.6441134909, 39.5400527406, 163.398160832],
 [37.5598048804, 1.34572784158, 83.4801551365],
 [88.1645062351, 95.1536625708, 466.265805791],
 [13.8346208354, 25.494048204, 100.886430268],
 [64.4108437467, 77.2598381277, 365.641048062],
 [68.925991798, 97.4536007955, 426.140015493],
 [39.4884422375, 50.8561281903, 235.532389457],
 [52.4631776831, 59.7765096878, 283.291640318],
 [48.4847869797, 66.9703542227, 298.581440375],
 [8.06208781377, 98.2426001448, 309.234108782],
 [32.7318877149, 18.8535355289, 129.610139015],
 [11.6523787962, 66.2645117418, 224.150542091],
 [13.7303535349, 70.4725091314, 235.305665631],
 [8.18555176536, 41.8519894198, 153.484189455],
 [53.6098761481, 94.560121637, 394.939444253],
 [95.3686098922, 47.2955069599, 336.126738879],
 [87.3336092062, 93.8039343271, 449.363351987],
 [66.3576110919, 81.8475512843, 387.014816485],
 [19.7547175302, 65.5233009197, 240.389441595],
 [21.1334404504, 47.4371819938, 177.14828058],
 [22.37386481, 25.9556275364, 119.61125795],
 [93.9904040537, 0.127890520058, 196.716166657],
 [86.7201980995, 18.413766785, 236.260808358],
 [98.9983729904, 60.2312656882, 384.381344695],
 [3.59396564372, 96.2522173231, 293.237183045],
 [15.1023633732, 92.5569035696, 304.890882807],
 [97.8341407695, 2.02390810433, 201.293598424],
 [19.9382196923, 46.7782734632, 170.610093035],
 [30.3735111369, 58.7775251616, 242.373484227],
 [73.2928831485, 67.6696277593, 353.082991304],
 [52.2309008804, 81.9024482531, 348.725688557],
 [86.4295761137, 66.5402275975, 365.959970954],
 [93.4008021441, 18.0752459352, 235.472381633],
 [13.213460059, 91.4888587787, 300.606878255],
 [4.59346270394, 46.3359315158, 145.818745251],
 [15.6692915825, 35.5437439971, 138.880334695],
 [52.9593597724, 68.7202096086, 317.163707741],
 [56.8175212312, 47.5727319202, 254.903631301],
 [51.1335430813, 78.0421674552, 334.5843335],
 [7.86216471526, 17.7290817759, 69.3555888141],
 [54.6986037014, 92.7445841407, 386.859937239],
 [86.3990630133, 41.8886945857, 294.871713576],
 [11.9475060186, 42.9613867358, 156.754219545],
 [70.3584010648, 83.7062345104, 391.806135291],
 [29.0223663255, 84.327783082, 319.310462851],
 [42.7594799067, 97.4933260814, 376.291589478],
 [96.2156564389, 25.8342825832, 280.617043873],
 [53.2277276552, 27.9055085669, 194.430465068],
 [30.3609896715, 0.939644215313, 69.6488631767],
 [83.2775653897, 73.1793485695, 384.597184993],
 [30.1876924786, 7.1465385989, 89.5390083986],
 [11.7884184617, 51.6977608445, 181.550682802],
 [18.2924240117, 61.9779760484, 224.773382884],
 [96.7126676927, 9.0291015125, 219.567093701],
 [31.0127386947, 78.2833824603, 298.490216481],
 [11.3972607536, 61.728693243, 199.944044715],
 [17.3925557906, 4.24114086314, 43.9156923531],
 [72.1826937267, 34.5390721676, 256.068378234],
 [73.980020785, 3.71649343826, 159.372580639],
 [94.4930583509, 88.41719702, 447.132703621],
 [84.5628207335, 20.2411621935, 233.078829579],
 [51.7424739723, 11.009747964, 131.070179635],
 [53.7485903953, 60.0251022958, 298.814332704],
 [85.0508347563, 95.7369969538, 451.80352299],
 [46.7772504514, 90.2022062395, 368.366435952],
 [49.7584341737, 52.834494361, 254.706774007],
 [24.1192565017, 42.1028107802, 168.308432759],
 [27.2015764537, 29.9787492892, 146.34226],
 [7.00959616769, 55.876058392, 176.810148976],
 [97.6469496688, 8.14762512696, 219.16028041],
 [1.38298250945, 84.9440869198, 252.905652954],
 [22.3235303534, 27.5150750402, 127.570478844],
 [45.0454062325, 93.5204022248, 375.822340339],
 [40.1639914677, 0.161699234822, 80.3890193252],
 [53.182739793, 8.17031616228, 142.718183077],
 [46.4567791559, 82.000170914, 336.876154384],
 [77.1303006946, 95.1887594549, 438.460586127],
 [68.600607572, 72.5711807231, 355.900286918],
 [41.6938871165, 69.241125973, 284.834636711],
 [4.1426693978, 52.2547263792, 168.034400947],
 [17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],
 [65.1003018959, 33.3538834975, 231.711507921],
 [24.6441134909, 39.5400527406, 163.398160832],
 [37.5598048804, 1.34572784158, 83.4801551365],
 [88.1645062351, 95.1536625708, 466.265805791],
 [13.8346208354, 25.494048204, 100.886430268],
 [64.4108437467, 77.2598381277, 365.641048062],
 [68.925991798, 97.4536007955, 426.140015493],
 [39.4884422375, 50.8561281903, 235.532389457],
 [52.4631776831, 59.7765096878, 283.291640318],
 [48.4847869797, 66.9703542227, 298.581440375],
 [8.06208781377, 98.2426001448, 309.234108782],
 [32.7318877149, 18.8535355289, 129.610139015],
 [11.6523787962, 66.2645117418, 224.150542091],
 [13.7303535349, 70.4725091314, 235.305665631],
 [8.18555176536, 41.8519894198, 153.484189455],
 [53.6098761481, 94.560121637, 394.939444253],
 [95.3686098922, 47.2955069599, 336.126738879],
 [87.3336092062, 93.8039343271, 449.363351987],
 [66.3576110919, 81.8475512843, 387.014816485],
 [19.7547175302, 65.5233009197, 240.389441595],
 [21.1334404504, 47.4371819938, 177.14828058],
 [22.37386481, 25.9556275364, 119.61125795],
 [93.9904040537, 0.127890520058, 196.716166657],
 [86.7201980995, 18.413766785, 236.260808358],
 [98.9983729904, 60.2312656882, 384.381344695],
 [3.59396564372, 96.2522173231, 293.237183045],
 [15.1023633732, 92.5569035696, 304.890882807],
 [97.8341407695, 2.02390810433, 201.293598424],
 [19.9382196923, 46.7782734632, 170.610093035],
 [30.3735111369, 58.7775251616, 242.373484227],
 [73.2928831485, 67.6696277593, 353.082991304],
 [52.2309008804, 81.9024482531, 348.725688557],
 [86.4295761137, 66.5402275975, 365.959970954],
 [93.4008021441, 18.0752459352, 235.472381633],
 [13.213460059, 91.4888587787, 300.606878255],
 [4.59346270394, 46.3359315158, 145.818745251],
 [15.6692915825, 35.5437439971, 138.880334695],
 [52.9593597724, 68.7202096086, 317.163707741],
 [56.8175212312, 47.5727319202, 254.903631301],
 [51.1335430813, 78.0421674552, 334.5843335],
 [7.86216471526, 17.7290817759, 69.3555888141],
 [54.6986037014, 92.7445841407, 386.859937239],
 [86.3990630133, 41.8886945857, 294.871713576],
 [11.9475060186, 42.9613867358, 156.754219545],
 [70.3584010648, 83.7062345104, 391.806135291],
 [29.0223663255, 84.327783082, 319.310462851],
 [42.7594799067, 97.4933260814, 376.291589478],
 [96.2156564389, 25.8342825832, 280.617043873],
 [53.2277276552, 27.9055085669, 194.430465068],
 [30.3609896715, 0.939644215313, 69.6488631767],
 [83.2775653897, 73.1793485695, 384.597184993],
 [30.1876924786, 7.1465385989, 89.5390083986],
 [11.7884184617, 51.6977608445, 181.550682802],
 [18.2924240117, 61.9779760484, 224.773382884],
 [96.7126676927, 9.0291015125, 219.567093701],
 [31.0127386947, 78.2833824603, 298.490216481],
 [11.3972607536, 61.728693243, 199.944044715],
 [17.3925557906, 4.24114086314, 43.9156923531],
 [72.1826937267, 34.5390721676, 256.068378234],
 [73.980020785, 3.71649343826, 159.372580639],
 [94.4930583509, 88.41719702, 447.132703621],
 [84.5628207335, 20.2411621935, 233.078829579],
 [51.7424739723, 11.009747964, 131.070179635],
 [53.7485903953, 60.0251022958, 298.814332704],
 [85.0508347563, 95.7369969538, 451.80352299],
 [46.7772504514, 90.2022062395, 368.366435952],
 [49.7584341737, 52.834494361, 254.706774007],
 [24.1192565017, 42.1028107802, 168.308432759],
 [27.2015764537, 29.9787492892, 146.34226],
 [7.00959616769, 55.876058392, 176.810148976],
 [97.6469496688, 8.14762512696, 219.16028041],
 [1.38298250945, 84.9440869198, 252.905652954],
 [22.3235303534, 27.5150750402, 127.570478844],
 [45.0454062325, 93.5204022248, 375.822340339],
 [40.1639914677, 0.161699234822, 80.3890193252],
 [53.182739793, 8.17031616228, 142.718183077],
 [46.4567791559, 82.000170914, 336.876154384],
 [77.1303006946, 95.1887594549, 438.460586127],
 [68.600607572, 72.5711807231, 355.900286918],
 [41.6938871165, 69.241125973, 284.834636711],
 [4.1426693978, 52.2547263792, 168.034400947],
 [17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],

In [8]:
#ahora lo que nos quedó es una lista con los datos que importamos:
fila

['4.1426693978', '52.2547263792', '168.034400947']

In [9]:
dato

[4.1426693978, 52.2547263792, 168.034400947]

In [10]:
final = np.array(datos)
final

array([[1.79302012e+01, 9.45205920e+01, 3.20259530e+02],
       [9.71446972e+01, 6.95932820e+01, 4.04634472e+02],
       [8.17759008e+01, 5.73764810e+00, 1.81485108e+02],
       [5.58543424e+01, 7.03259017e+01, 3.21773638e+02],
       [4.93665500e+01, 7.51140402e+01, 3.22465486e+02],
       [3.19270247e+00, 2.92562989e+01, 9.46188109e+01],
       [4.92007841e+01, 8.61444385e+01, 3.56348093e+02],
       [2.18828039e+01, 4.68415052e+01, 1.81653769e+02],
       [7.95098627e+01, 8.73973555e+01, 4.23557743e+02],
       [8.81538875e+01, 6.52056419e+01, 3.69229245e+02],
       [6.07438543e+01, 9.99576339e+01, 4.27605804e+02],
       [6.74155819e+01, 5.03683096e+01, 2.92471822e+02],
       [4.83181158e+01, 9.91289531e+01, 3.95529811e+02],
       [2.88299720e+01, 8.71849489e+01, 3.19031348e+02],
       [4.38537427e+01, 6.44736391e+01, 2.87428144e+02],
       [2.53136941e+01, 8.35452943e+01, 2.92768909e+02],
       [1.08077267e+01, 4.56955686e+01, 1.59663308e+02],
       [9.83657459e+01, 8.26973935e+01, 4.38798964e+02],
       [2.91469100e+01, 6.63651068e+01, 2.50986309e+02],
       [6.51003019e+01, 3.33538835e+01, 2.31711508e+02],
       [2.46441135e+01, 3.95400527e+01, 1.63398161e+02],
       [3.75598049e+01, 1.34572784e+00, 8.34801551e+01],
       [8.81645062e+01, 9.51536626e+01, 4.66265806e+02],
       [1.38346208e+01, 2.54940482e+01, 1.00886430e+02],
       [6.44108437e+01, 7.72598381e+01, 3.65641048e+02],
       [6.89259918e+01, 9.74536008e+01, 4.26140015e+02],
       [3.94884422e+01, 5.08561282e+01, 2.35532389e+02],
       [5.24631777e+01, 5.97765097e+01, 2.83291640e+02],
       [4.84847870e+01, 6.69703542e+01, 2.98581440e+02],
       [8.06208781e+00, 9.82426001e+01, 3.09234109e+02],
       [3.27318877e+01, 1.88535355e+01, 1.29610139e+02],
       [1.16523788e+01, 6.62645117e+01, 2.24150542e+02],
       [1.37303535e+01, 7.04725091e+01, 2.35305666e+02],
       [8.18555177e+00, 4.18519894e+01, 1.53484189e+02],
       [5.36098761e+01, 9.45601216e+01, 3.94939444e+02],
       [9.53686099e+01, 4.72955070e+01, 3.36126739e+02],
       [8.73336092e+01, 9.38039343e+01, 4.49363352e+02],
       [6.63576111e+01, 8.18475513e+01, 3.87014816e+02],
       [1.97547175e+01, 6.55233009e+01, 2.40389442e+02],
       [2.11334405e+01, 4.74371820e+01, 1.77148281e+02],
       [2.23738648e+01, 2.59556275e+01, 1.19611258e+02],
       [9.39904041e+01, 1.27890520e-01, 1.96716167e+02],
       [8.67201981e+01, 1.84137668e+01, 2.36260808e+02],
       [9.89983730e+01, 6.02312657e+01, 3.84381345e+02],
       [3.59396564e+00, 9.62522173e+01, 2.93237183e+02],
       [1.51023634e+01, 9.25569036e+01, 3.04890883e+02],
       [9.78341408e+01, 2.02390810e+00, 2.01293598e+02],
       [1.99382197e+01, 4.67782735e+01, 1.70610093e+02],
       [3.03735111e+01, 5.87775252e+01, 2.42373484e+02],
       [7.32928831e+01, 6.76696278e+01, 3.53082991e+02],
       [5.22309009e+01, 8.19024483e+01, 3.48725689e+02],
       [8.64295761e+01, 6.65402276e+01, 3.65959971e+02],
       [9.34008021e+01, 1.80752459e+01, 2.35472382e+02],
       [1.32134601e+01, 9.14888588e+01, 3.00606878e+02],
       [4.59346270e+00, 4.63359315e+01, 1.45818745e+02],
       [1.56692916e+01, 3.55437440e+01, 1.38880335e+02],
       [5.29593598e+01, 6.87202096e+01, 3.17163708e+02],
       [5.68175212e+01, 4.75727319e+01, 2.54903631e+02],
       [5.11335431e+01, 7.80421675e+01, 3.34584334e+02],
       [7.86216472e+00, 1.77290818e+01, 6.93555888e+01],
       [5.46986037e+01, 9.27445841e+01, 3.86859937e+02],
       [8.63990630e+01, 4.18886946e+01, 2.94871714e+02],
       [1.19475060e+01, 4.29613867e+01, 1.56754220e+02],
       [7.03584011e+01, 8.37062345e+01, 3.91806135e+02],
       [2.90223663e+01, 8.43277831e+01, 3.19310463e+02],
       [4.27594799e+01, 9.74933261e+01, 3.76291589e+02],
       [9.62156564e+01, 2.58342826e+01, 2.80617044e+02],
       [5.32277277e+01, 2.79055086e+01, 1.94430465e+02],
       [3.03609897e+01, 9.39644215e-01, 6.96488632e+01],
       [8.32775654e+01, 7.31793486e+01, 3.84597185e+02],
       [3.01876925e+01, 7.14653860e+00, 8.95390084e+01],
       [1.17884185e+01, 5.16977608e+01, 1.81550683e+02],
       [1.82924240e+01, 6.19779760e+01, 2.24773383e+02],
       [9.67126677e+01, 9.02910151e+00, 2.19567094e+02],
       [3.10127387e+01, 7.82833825e+01, 2.98490216e+02],
       [1.13972608e+01, 6.17286932e+01, 1.99944045e+02],
       [1.73925558e+01, 4.24114086e+00, 4.39156924e+01],
       [7.21826937e+01, 3.45390722e+01, 2.56068378e+02],
       [7.39800208e+01, 3.71649344e+00, 1.59372581e+02],
       [9.44930584e+01, 8.84171970e+01, 4.47132704e+02],
       [8.45628207e+01, 2.02411622e+01, 2.33078830e+02],
       [5.17424740e+01, 1.10097480e+01, 1.31070180e+02],
       [5.37485904e+01, 6.00251023e+01, 2.98814333e+02],
       [8.50508348e+01, 9.57369970e+01, 4.51803523e+02],
       [4.67772505e+01, 9.02022062e+01, 3.68366436e+02],
       [4.97584342e+01, 5.28344944e+01, 2.54706774e+02],
       [2.41192565e+01, 4.21028108e+01, 1.68308433e+02],
       [2.72015765e+01, 2.99787493e+01, 1.46342260e+02],
       [7.00959617e+00, 5.58760584e+01, 1.76810149e+02],
       [9.76469497e+01, 8.14762513e+00, 2.19160280e+02],
       [1.38298251e+00, 8.49440869e+01, 2.52905653e+02],
       [2.23235304e+01, 2.75150750e+01, 1.27570479e+02],
       [4.50454062e+01, 9.35204022e+01, 3.75822340e+02],
       [4.01639915e+01, 1.61699235e-01, 8.03890193e+01],
       [5.31827398e+01, 8.17031616e+00, 1.42718183e+02],
       [4.64567792e+01, 8.20001709e+01, 3.36876154e+02],
       [7.71303007e+01, 9.51887595e+01, 4.38460586e+02],
       [6.86006076e+01, 7.25711807e+01, 3.55900287e+02],
       [4.16938871e+01, 6.92411260e+01, 2.84834637e+02],
       [4.14266940e+00, 5.22547264e+01, 1.68034401e+02]])

In [11]:
final[0] #vamos a ver como nos quedaron convertidos a números

array([ 17.93020121,  94.52059195, 320.2595296 ])

In [12]:
final.shape #debe haber 100 filas y 3 columnas

(100, 3)

In [13]:
#Usando pandas es mucho mas fácil!
finalp=pd.read_csv("datos_pandas.csv",header=None)

In [14]:
type(finalp) #el tipo de datos es un dataframe

pandas.core.frame.DataFrame

In [15]:
finalp.info() # arroja una especie de resumen del elemento pasado

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB

In [16]:
finalp.head()
#tiene una 1ra fila con los nombres de las columnas y la 1ra columna identifica cada fila

           0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

In [17]:
finalp.tail() #las ultimas 6 filas

            0          1           2
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

In [18]:
#los primeros datos de la primera columna se obtinene asi
finalp[0].head()

0    17.930201
1    97.144697
2    81.775901
3    55.854342
4    49.366550
Name: 0, dtype: float64

In [19]:
#para obtener la 1ra fila (o cualquier fila que necesitemos)
finalp.iloc[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [20]:
#tambien se puede obtener las filas que tienen los valores de la 1ra columna que cumplan cierta condición, por ej <1
finalp[finalp[0]<4]

           0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
90  1.382983  84.944087  252.905653

In [21]:
finalp[(finalp[0]<4) | (finalp[2]>450)] #en python se usa | para la condicion OR y & para el AND

            0          1           2
5    3.192702  29.256299   94.618811
22  88.164506  95.153663  466.265806
44   3.593966  96.252217  293.237183
83  85.050835  95.736997  451.803523
90   1.382983  84.944087  252.905653

In [22]:
#miremos cual es el resultado de la 1ra comparación
# devuelve un vector de booleanos segun el cumplimiento o no de la condición
finalp[0]<4

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: 0, Length: 100, dtype: bool

In [23]:
finalp.columns #vemos el nombre de las columnas

Int64Index([0, 1, 2], dtype='int64')

In [24]:
finalp.columns=["Col0","Col1","Col2"] # cambiar nombre de las columnas

In [25]:
finalp.head() # resultado de la función anterior

        Col0       Col1        Col2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

In [26]:
#entonces podemos usar esos nombres para llamar a los datos de dichas columnas de una forma diferente
finalp.Col0.iloc[0:3]

0    17.930201
1    97.144697
2    81.775901
Name: Col0, dtype: float64

In [28]:
finalp["Col1_Col2"]=finalp.apply(lambda row:row["Col2"]+row["Col1"], axis=1) 
# asi creamos una nueva variable "Col1_Col2" del elemento "finalp"
# la función "apply()" aplica una función al parametro "axis" pasado dentro de ella
# en este caso aplicará al "axis=1", es decir, columnas; 

# la función Lambda():
# la usamos porque estamos definiendo ubna función que podemos escribir en una sola linea de codigo
# vendría a ser como la versión corta de utilizar "def"
# axis=1 es para que la operación sea columna a columna, axis=0 es por filas

# en este caso definimos que
# desde la fila 0 hasta el final de las filas de contenga la columna "Col2"
# sumaremos"Col2" y "Col1" y almacenaremos su resultado en "Col1_Col2"
finalp

         Col0       Col1        Col2   Col1_Col2
0   17.930201  94.520592  320.259530  414.780122
1   97.144697  69.593282  404.634472  474.227754
2   81.775901   5.737648  181.485108  187.222756
3   55.854342  70.325902  321.773638  392.099540
4   49.366550  75.114040  322.465486  397.579526
..        ...        ...         ...         ...
95  46.456779  82.000171  336.876154  418.876325
96  77.130301  95.188759  438.460586  533.649346
97  68.600608  72.571181  355.900287  428.471468
98  41.693887  69.241126  284.834637  354.075763
99   4.142669  52.254726  168.034401  220.289127

[100 rows x 4 columns]

In [29]:
finalp=finalp.drop("Col1_Col2", axis=1) #para eliminar la columna
finalp

         Col0       Col1        Col2
0   17.930201  94.520592  320.259530
1   97.144697  69.593282  404.634472
2   81.775901   5.737648  181.485108
3   55.854342  70.325902  321.773638
4   49.366550  75.114040  322.465486
..        ...        ...         ...
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

[100 rows x 3 columns]

In [30]:
#ahora vamos a crear dataframes con los datos a mano, a partir de listas
usuarios=[1,2,3]
nombres=["juan","maria","luis"]

In [31]:
print(nombres, usuarios)

['juan', 'maria', 'luis'] [1, 2, 3]

In [33]:
data=pd.DataFrame(list(zip(usuarios, #la función zi: es utilizada para mapear los mismos índices en más de un iterable.
                           nombres)),#entonces lo que hara es a las varaibles 'usuarios' y 'nombres' les asignará el mismo indice
                  columns=['usuarios',
                           'nombres'])                    
data

   usuarios nombres
0         1    juan
1         2   maria
2         3    luis

In [34]:
#vemos que el tipo es correcto
type(data)

pandas.core.frame.DataFrame

In [35]:
#ahora crearemos otro con los mismos Ids pero otros datos
Ids=[1,2,1,1,1,3,3,2,1,2,2,2]
publicidad=[101,105,108,400,203,198,209,115,274,222,734,219]

In [37]:
#Ahora deberas crear un nuevo dataframe con estos datos y llamarlo ads, las columnas seran usuarios, ad_id
ads=pd.DataFrame(list(zip(Ids,
                          publicidad)),
                 columns=['usuarios',
                          'publicidades']) 
ads

    usuarios  publicidades
0          1           101
1          2           105
2          1           108
3          1           400
4          1           203
5          3           198
6          3           209
7          2           115
8          1           274
9          2           222
10         2           734
11         2           219

In [38]:
#lo que debemos hacer ahora es un "join" entre ambas listas

df=pd.merge(data,
            ads, 
            on='usuarios')

In [39]:
df #vemos que justamente joineó por el camo usuarios y quedó la data en un solo dataframe

    usuarios nombres  publicidades
0          1    juan           101
1          1    juan           108
2          1    juan           400
3          1    juan           203
4          1    juan           274
5          2   maria           105
6          2   maria           115
7          2   maria           222
8          2   maria           734
9          2   maria           219
10         3    luis           198
11         3    luis           209

In [ ]:
type(df)